using System;
using System.Collections.Generic;
using System.Linq;

namespace JevGen.Generator;

/// <summary>
/// Emits the generated client, its cached schema and its registration for one contract.
/// </summary>
/// <remarks>
/// The output is deliberately plain and deterministic: no reflection, no expression trees, no
/// dictionaries in the hot path. Question metadata is built once into static readonly fields
/// and reused for every call, so the per-call work is building a request record and mapping a
/// response.
/// </remarks>
internal static partial class ClientEmitter
{
    private const string Jg = "global::JevGen.";
    private const string Immutable = "global::System.Collections.Immutable.";
    private const string Generic = "global::System.Collections.Generic.";

    internal static string Emit(ClientModel client)
    {
        var source = new SourceBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("// Generated by JevGen. Do not edit; your changes will be overwritten.");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        source.AppendLine();

        using (source.Block("namespace " + client.GeneratedNamespace))
        {
            EmitSchema(source, client);
            source.AppendLine();
            EmitClient(source, client);
            source.AppendLine();
            EmitRegistration(source, client);
        }

        return source.ToString();
    }

    private static void EmitGeneratedCodeAttribute(SourceBuilder source)
        => source.AppendLine(
            $"[global::System.CodeDom.Compiler.GeneratedCode({SourceBuilder.Literal(KnownNames.ToolName)}, " +
            $"{SourceBuilder.Literal(KnownNames.ToolVersion)})]");

    // ---------------------------------------------------------------- schema

    private static void EmitSchema(SourceBuilder source, ClientModel client)
    {
        source.AppendLine("/// <summary>Cached question metadata, request construction and result mapping for " + client.InterfaceName + ".</summary>");
        EmitGeneratedCodeAttribute(source);
        source.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");

        using (source.Block("internal static class " + client.SchemaTypeName))
        {
            EmitEmptyProviderOptions(source);

            foreach (var method in client.Methods)
            {
                EmitQuestionDefinitions(source, client, method);
                EmitStateTypeInfo(source, method);
                EmitProviderOptions(source, client, method);
                EmitRequestFactory(source, client, method);
            }

            foreach (var method in client.Methods)
            {
                foreach (var question in method.Questions)
                {
                    EmitQuestionMapper(source, method, question);
                }
            }

            foreach (var enumType in ChoiceEnums(client))
            {
                EmitEnumMappers(source, enumType.Key, enumType.Value);
            }

            foreach (var method in client.Methods)
            {
                EmitResponseMapper(source, method);
            }

            EmitDescriptor(source, client);
        }
    }

    private static void EmitEmptyProviderOptions(SourceBuilder source)
    {
        source.AppendLine(
            $"private static readonly {Generic}IReadOnlyDictionary<string, {Generic}IReadOnlyDictionary<string, object?>> NoProviderOptions =");
        source.AppendLine(
            $"    new {Generic}Dictionary<string, {Generic}IReadOnlyDictionary<string, object?>>(0);");
        source.AppendLine();
    }

    private static void EmitQuestionDefinitions(SourceBuilder source, ClientModel client, MethodModel method)
    {
        source.AppendLine(
            $"internal static readonly {Immutable}ImmutableArray<{Jg}JevQuestionDefinition> {method.Name}_Questions =");
        source.AppendLine($"    {Immutable}ImmutableArray.Create<{Jg}JevQuestionDefinition>(");

        var questions = method.Questions.Values;

        for (var index = 0; index < questions.Length; index++)
        {
            EmitQuestionDefinition(source, client, method, questions[index], index == questions.Length - 1);
        }

        source.AppendLine("    );");
        source.AppendLine();
    }

    private static void EmitQuestionDefinition(
        SourceBuilder source,
        ClientModel client,
        MethodModel method,
        QuestionModel question,
        bool isLast)
    {
        var model = question.Model ?? method.Model ?? client.Model;
        var provider = question.Provider ?? method.Provider ?? client.Provider;

        source.AppendLine($"        new {Jg}JevQuestionDefinition");
        source.AppendLine("        {");
        source.AppendLine($"            Id = {SourceBuilder.Literal(question.Id)},");
        source.AppendLine($"            Kind = {Jg}JevQuestionKind.{question.Kind},");
        source.AppendLine($"            Prompt = {SourceBuilder.Literal(question.Prompt)},");

        if (!question.Options.IsEmpty)
        {
            source.AppendLine($"            Options = {Immutable}ImmutableArray.Create<{Jg}JevChoiceOption>(");

            var options = question.Options.Values;

            for (var index = 0; index < options.Length; index++)
            {
                var option = options[index];
                var separator = index == options.Length - 1 ? string.Empty : ",";
                source.AppendLine(
                    $"                new {Jg}JevChoiceOption({SourceBuilder.Literal(option.Id)}, " +
                    $"{SourceBuilder.Literal(option.Criteria)}){separator}");
            }

            source.AppendLine("            ),");
        }

        if (question.Minimum is { } minimum)
        {
            source.AppendLine($"            Minimum = {SourceBuilder.Number(minimum)},");
        }

        if (question.Maximum is { } maximum)
        {
            source.AppendLine($"            Maximum = {SourceBuilder.Number(maximum)},");
        }

        if (!question.Criteria.IsEmpty)
        {
            var labels = string.Join(", ", question.Criteria.Values.Select(SourceBuilder.Literal));
            source.AppendLine($"            Criteria = {Immutable}ImmutableArray.Create<string>({labels}),");
        }

        if (model is not null)
        {
            source.AppendLine($"            Model = {SourceBuilder.Literal(model)},");
        }

        if (provider is not null)
        {
            source.AppendLine($"            Provider = {SourceBuilder.Literal(provider)},");
        }

        if (question.RequiresProbabilities)
        {
            source.AppendLine("            RequiresProbabilities = true,");
        }

        source.AppendLine("        }" + (isLast ? string.Empty : ","));
    }

    private static void EmitStateTypeInfo(SourceBuilder source, MethodModel method)
    {
        if (method.HasComposedState)
        {
            return;
        }

        var field = "_stateTypeInfo_" + method.Name;

        source.AppendLine($"private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? {field};");
        source.AppendLine();
        source.AppendLine($"private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? StateTypeInfo_{method.Name}");
        source.AppendLine($"    => {field} ??= {Jg}JevGenJson.TryGetTypeInfo(typeof({method.StateTypeName}));");
        source.AppendLine();
    }

    private static void EmitProviderOptions(SourceBuilder source, ClientModel client, MethodModel method)
    {
        var declared = client.ProviderOptions.Values.Concat(method.ProviderOptions.Values).ToList();

        if (declared.Count == 0)
        {
            return;
        }

        source.AppendLine(
            $"private static readonly {Generic}IReadOnlyDictionary<string, {Generic}IReadOnlyDictionary<string, object?>> " +
            $"ProviderOptions_{method.Name} = BuildProviderOptions_{method.Name}();");
        source.AppendLine();

        using (source.Block(
            $"private static {Generic}IReadOnlyDictionary<string, {Generic}IReadOnlyDictionary<string, object?>> " +
            $"BuildProviderOptions_{method.Name}()"))
        {
            source.AppendLine(
                $"var byProvider = new {Generic}Dictionary<string, {Generic}IReadOnlyDictionary<string, object?>>(" +
                "global::System.StringComparer.OrdinalIgnoreCase);");

            foreach (var group in declared.GroupBy(option => option.Provider, StringComparer.OrdinalIgnoreCase))
            {
                var local = "options_" + SourceBuilder.Identifier(group.Key);
                source.AppendLine(
                    $"var {local} = new {Generic}Dictionary<string, object?>(global::System.StringComparer.Ordinal);");

                foreach (var option in group)
                {
                    source.AppendLine(
                        $"{local}[{SourceBuilder.Literal(option.Key)}] = {SourceBuilder.Literal(option.Value)};");
                }

                source.AppendLine($"byProvider[{SourceBuilder.Literal(group.Key)}] = {local};");
            }

            source.AppendLine("return byProvider;");
        }

        source.AppendLine();
    }

    private static void EmitRequestFactory(SourceBuilder source, ClientModel client, MethodModel method)
    {
        var parameters = BuildParameterList(method);
        var hasOptions = !client.ProviderOptions.IsEmpty || !method.ProviderOptions.IsEmpty;

        source.AppendLine($"/// <summary>Builds the evaluation request for <c>{client.InterfaceName}.{method.Name}</c>.</summary>");

        using (source.Block($"internal static {Jg}EvaluationRequest Create{method.Name}Request({parameters})"))
        {
            string stateExpression;
            string stateTypeInfoExpression;

            if (method.HasComposedState)
            {
                var count = method.ContextParameters.Length + 1;
                source.AppendLine(
                    $"var state = new {Generic}Dictionary<string, global::System.Text.Json.JsonElement>({count}, " +
                    "global::System.StringComparer.Ordinal);");

                var stateKey = method.StateName ?? method.StateParameterName;
                source.AppendLine(
                    $"state[{SourceBuilder.Literal(stateKey)}] = {Jg}JevCompositeState.Part<{method.StateTypeName}>({method.StateParameterName});");

                foreach (var context in method.ContextParameters)
                {
                    source.AppendLine(
                        $"state[{SourceBuilder.Literal(context.Name)}] = {Jg}JevCompositeState.Part<{context.TypeName}>({context.ParameterName});");
                }

                source.AppendLine();
                stateExpression = "state";
                stateTypeInfoExpression = $"{Jg}JevCompositeState.TypeInfo";
            }
            else
            {
                stateExpression = method.StateParameterName;
                stateTypeInfoExpression = $"StateTypeInfo_{method.Name}";
            }

            source.AppendLine($"return new {Jg}EvaluationRequest");
            source.AppendLine("{");
            source.AppendLine($"    State = {stateExpression},");
            source.AppendLine($"    StateTypeInfo = {stateTypeInfoExpression},");
            source.AppendLine($"    Questions = {method.Name}_Questions,");
            source.AppendLine($"    ClientName = {SourceBuilder.Literal(client.DisplayName)},");
            source.AppendLine($"    MethodName = {SourceBuilder.Literal(method.Name)},");
            source.AppendLine($"    ContractVersion = {SourceBuilder.Literal(client.ContractVersion)},");
            source.AppendLine($"    Model = {SourceBuilder.Literal(method.Model ?? client.Model)},");
            source.AppendLine($"    Provider = {SourceBuilder.Literal(method.Provider ?? client.Provider)},");
            source.AppendLine($"    ProviderOptions = {(hasOptions ? "ProviderOptions_" + method.Name : "NoProviderOptions")},");
            source.AppendLine("};");
        }

        source.AppendLine();
    }

    private static string BuildParameterList(MethodModel method)
    {
        var parameters = new List<string> { $"{method.StateTypeName} {method.StateParameterName}" };

        parameters.AddRange(
            method.ContextParameters.Values.Select(context => $"{context.TypeName} {context.ParameterName}"));

        return string.Join(", ", parameters);
    }

    private static IEnumerable<QuestionModel> AllQuestions(ClientModel client)
        => client.Methods.Values.SelectMany(method => method.Questions.Values);

    private static Dictionary<string, EquatableArray<ChoiceOptionModel>> ChoiceEnums(ClientModel client)
    {
        var enums = new Dictionary<string, EquatableArray<ChoiceOptionModel>>(StringComparer.Ordinal);

        foreach (var question in AllQuestions(client))
        {
            if (question.ChoiceTypeName is { } name && !enums.ContainsKey(name))
            {
                enums[name] = question.Options;
            }
        }

        return enums;
    }
}
