using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace JevGen.Generator;

/// <summary>
/// The serializer contexts an assembly has declared for JevGen, gathered once per compilation.
/// </summary>
internal sealed record JsonContextModel(EquatableArray<string> ContextTypeNames)
{
    internal static JsonContextModel From(Compilation compilation)
    {
        var names = ImmutableArray.CreateBuilder<string>();

        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (!attribute.Matches(KnownNames.JevJsonContextAttribute)
                || attribute.ConstructorArguments.Length == 0
                || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol contextType)
            {
                continue;
            }

            names.Add(contextType.ToFullyQualified());
        }

        return new JsonContextModel(new EquatableArray<string>(names.ToImmutable()));
    }
}

/// <summary>
/// Emits the per-assembly bootstrap that hands the declared serializer contexts to JevGen.
/// </summary>
/// <remarks>
/// Source generators cannot see one another's output, so JevGen cannot emit
/// <c>[JsonSerializable]</c> declarations and expect <c>System.Text.Json</c> to process them.
/// Instead the application declares its own context and names it with
/// <c>[assembly: JevJsonContext(...)]</c>; this bootstrap wires it up at module load, which
/// keeps state serialization completely reflection-free and therefore AOT- and trim-safe.
/// </remarks>
internal static class JsonBootstrapEmitter
{
    internal static string Emit(JsonContextModel model)
    {
        var source = new SourceBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("// Generated by JevGen. Do not edit; your changes will be overwritten.");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591");
        source.AppendLine();

        using (source.Block("namespace JevGen.Generated"))
        {
            source.AppendLine("/// <summary>Registers this assembly's serializer contexts with JevGen at module load.</summary>");
            source.AppendLine(
                "[global::System.CodeDom.Compiler.GeneratedCode(" +
                SourceBuilder.Literal(KnownNames.ToolName) + ", " +
                SourceBuilder.Literal(KnownNames.ToolVersion) + ")]");

            using (source.Block("internal static class JevGenAssemblyJson"))
            {
                source.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                using (source.Block("internal static void Initialize()"))
                {
                    foreach (var contextType in model.ContextTypeNames.Values.Distinct())
                    {
                        source.AppendLine($"global::JevGen.JevGenJson.AddContext({contextType}.Default);");
                    }
                }
            }
        }

        return source.ToString();
    }
}
